spring:
  application:
    name: osca

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:23306/osca?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
      username: osca
      password: osca
      driver-class-name: com.mysql.cj.jdbc.Driver

      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 3000
      leak-detection-threshold: 60000

server:
  port: 10000

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://db.ascode.click/osca?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul

---
spring:
  config:
    activate:
      on-profile: ci

  flyway:
    enabled: false